# Generated by Django 2.2.2 on 2019-07-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageTitle', models.CharField(max_length=100)),
                ('audioFile', models.FileField(upload_to='uploads/')),
                ('notesDisplay', models.CharField(max_length=200)),
            ],
        ),
    ]
