# Generated by Django 2.2.2 on 2019-07-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190707_1610'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notecheck',
            table='notecheck',
        ),
    ]
